# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseFile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
      pod 'AFNetworking'
      pod 'YYModel'
      pod 'MJRefresh'
  #    pod 'lottie-ios'
      pod 'SDWebImage'
      pod 'SVProgressHUD'
end
